config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :leagues
  resources :nba_teams
  resources :nfl_teams

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

  def index
  end
  
end

app/controllers/nba_teams_controller.rb
class NbaTeamsController < ApplicationController

  def index
  end
  
end

app/controllers/nfl_teams_controller.rb
class NflTeamsController < ApplicationController

  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/nba_teams_helper.rb
module NbaTeamsHelper
end

app/helpers/nfl_teams_helper.rb
module NflTeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yourteamsucks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Your Team Sucks', root_path, class: 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Sign In</a></li>
          <li><a href="#">Sign Up</a></li>
          <li class="dropdown">
            <a href= '#' class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Leagues <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'NFL', nfl_teams_path %> </li>
              <li><%= link_to 'NBA', nba_teams_path %> </li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


<%= yield %>

</body>
</html>

app/views/leagues/index.html.erb
<div class='box col-xs-10 col-xs-offset-1 text-center'>

<h1> Pick the League </h1>

<h2 class = 'col-xs-5 col-xs-offset-1'>
  <%= link_to 'NFL', nfl_teams_path, class: 'btn btn-default btn-lg' %>
</h2>

<h2>
  <%= link_to 'NBA', nba_teams_path, class: 'btn btn-default btn-lg' %>
</h2>

</div>

app/views/nba_teams/index.html.erb
<div>

<h1 class= 'text-center'> NBA Teams </h1>
<br  />
  <div class='box col-xs-4 col-xs-offset-1'>
    <h3> Atlantic </h3>
      <hr />
      <h5> Boston Celtics </h5>
      <h5> Brooklyn Nets </h5>
      <h5> New York Knicks </h5>
      <h5> Philadelphia 76ers </h5>
      <h5> Toront Raptors </h5>
  </div>

  <div class='box col-xs-4 col-xs-offset-2'>
    <h3> Pacific</h3>
      <hr />
      <h5> Golden Stat Warriors </h5>
      <h5> LA Clippers </h5>
      <h5> Los Angeles Lakers </h5>
      <h5> Phoenix Suns </h5>
      <h5> Sacremento Kings </h5>
  </div>

  <div class='box col-xs-4 col-xs-offset-1'>
    <h3> Central </h3>
      <hr />
      <h5> Chicago Bulls </h5>
      <h5> Cleveland Cavaliers </h5>
      <h5> Detroit Pistons </h5>
      <h5> Indiana Pacers </h5>
      <h5> Milwaukee Bucks </h5>
  </div>

  <div class='box col-xs-4 col-xs-offset-2'>
    <h3> Soutwest </h3>
      <hr />
      <h5> Dallas Mavericks </h5>
      <h5> Houston Rockets </h5>
      <h5> Memphis Grizzlies </h5>
      <h5> New Orleans Pelicans </h5>
      <h5> San Antonio Spurs </h5>
  </div>

  <div class='box col-xs-4 col-xs-offset-1'>
    <h3> Southeast </h3>
      <hr />
      <h5> Atlanta Hawks </h5>
      <h5> Charlotte Hornets </h5>
      <h5> Miami Heat </h5>
      <h5> Orlando Magic </h5>
      <h5> Washington Wizards </h5>
  </div>

  <div class='box col-xs-4 col-xs-offset-2'>
    <h3> Northwest </h3>
      <hr />
      <h5> Denver Nuggets </h5>
      <h5> Minnesota Timberwolves </h5>
      <h5> Oklahoma City Thunder </h5>
      <h5> Portland Trail Blazers </h5>
      <h5> Utah Jazz </h5>
  </div>

</div>

app/views/nfl_teams/index.html.erb
<h1 class='text-center'> NFL Teams </h1>
<br  />
<br  />
<div class='box col-xs-4 col-xs-offset-1'>
  <h3> NFC East </h3>
  <hr />
    <h5> Dallas Cowboys </h5>
    <h5> New York Giants </h5>
    <h5> Philadelphia Eagles </h5>
    <h5> Washington Redskins </h5>
</div>

<div class='box col-xs-4 col-xs-offset-2'>
  <h3> AFC East </h3>
  <hr />
    <h5> Buffalo Bills </h5>
    <h5> Miami Dolphins </h5>
    <h5> New England Patriots </h5>
    <h5> New York Jets </h5>
</div>

<div class='box col-xs-4 col-xs-offset-1'>
  <h3> NFC West </h3>
  <hr />
    <h5> Arizona Cardinals </h5>
    <h5> Los Angeles Rams </h5>
    <h5> San Francisco 49ers </h5>
    <h5> Seattle Seahawks </h5>
</div>

<div class='box col-xs-4 col-xs-offset-2'>
  <h3> AFC West </h3>
  <hr />
    <h5> Denver Broncos </h5>
    <h5> Kansas City Chiefs </h5>
    <h5> Oakland Raiders </h5>
    <h5> San Diego Chargers </h5>
</div>

<div class='box col-xs-4 col-xs-offset-1'>
  <h3> NFC North </h3>
  <hr />
    <h5> Chicago Bears </h5>
    <h5> Detroit Lions </h5>
    <h5> Green Bay Packers </h5>
    <h5> Minnesota Vikings </h5>
</div>

<div class='box col-xs-4 col-xs-offset-2'>
  <h3> AFC North </h3>
  <hr />
    <h5> Baltimore Ravens </h5>
    <h5> Cincinnati Bengals </h5>
    <h5> Cleveland Browns </h5>
    <h5> Pittsburgh Steelers </h5>
</div>

<div class='box col-xs-4 col-xs-offset-1'>
  <h3> NFC South </h3>
  <hr />
    <h5> Atlanta Falcons </h5>
    <h5> Carolina Panthers </h5>
    <h5> New Orleans Saints </h5>
    <h5> Tampa Bay Buccaneers </h5>
</div>

<div class='box col-xs-4 col-xs-offset-2'>
  <h3> AFC South </h3>
  <hr />
    <h5> Houston Texans</h5>
    <h5> Indianapolis Colts </h5>
    <h5> Jacksonville Jaguars </h5>
    <h5> Tennessee Titans </h5>
</div>

app/views/welcome/index.html.erb
<div class='box col-xs-10 col-xs-offset-1'>
<h1 class='text-center'> Your Team Sucks </h1>

<h2 class='text-center'> Site Information </h2>


<h3 class='text-center'>
  <%= link_to 'Get Started', leagues_path, class: 'btn btn-primary' %>
</h3>
</div>